config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'user', to: "artists#index", as: :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :artists, only: :index do
    resources :albums, only: [:index, :edit, :update, :destroy]
  end

  resources :albums, only: [:new, :create]

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true
  validates :year, presence: true,
                   format: { with: /\A(19|[2-9][0-9])\d{2}\z/,
                             message: 'Needs to follow the format: yyyy' }
  validates :artist, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
require 'open-uri'

class Artist < ApplicationRecord
  has_many :albums, dependent: :destroy

  validates :name, presence: true,
                   uniqueness: true,
                   inclusion: { in: :artist_name_list, message: 'You need to choose between the options available.' }

  def artist_name_list
    artists = JSON.parse(open('https://run.mocky.io/v3/46ca2011-8b43-47cf-b3d7-4df003d48469/').read)
    artist_name_list = []
    artists.each do |element|
      artist_name_list << element.last['name']
    end
    artist_name_list
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:username]

  validates :username, uniqueness: true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_artist, only: [:index, :edit, :update, :destroy]
  before_action :set_album, only: [:edit, :update, :destroy]

  def index
    @albums = policy_scope(@artist.albums)
  end

  def new
    @artists = Artist.all
    @album = Album.new
    authorize @album
  end

  def create
    @album = Album.new(album_params)
    @artist = Artist.find(params[:album][:artist].to_i)
    @album.artist = @artist
    authorize @album
    if @album.save
      redirect_to artist_albums_path(@artist), notice: 'Your album was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to artist_albums_path(@artist), notice: "Your album was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to artist_albums_path(@artist), notice: 'Album was successfully deleted'
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def album_params
    params.require(:album).permit(:name, :year)
  end

  def set_album
    @album = Album.find(params[:id])
    authorize @album
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :username, :password, :admin)}

       devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :username, :password, :current_password)}
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = policy_scope(Artist)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-start">
    <h1 class="pt-5">Edit Album</h1>
  </div>

  <br>

  <% if policy(@album).edit? %>
    <div>
      <%= simple_form_for [@artist, @album] do |f| %>
        <%= f.input :name %>
        <%= f.input :year %>
        <%= f.submit 'Update', class: 'btn btn-primary' %>
        <%= link_to "Return to albums list", artist_albums_path(@artist), class: "btn btn-secondary" %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/albums/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <h2 class="mt-5 border-bottom"><strong> <%= @artist.name %>'s Albums</strong></h2>
  </div>
  <br>
  <div class="d-flex align-content-start flex-wrap">
    <% if @albums.present? %>
      <% @albums.each do |album| %>
        <div class="col-4 mb-3">
          <h2 class="border-bottom"><%= album.name %></h2>
          <p><strong>Year:</strong> <%= album.year %></p>
          <% if policy(album).edit? %>
            <%= link_to "Edit", edit_artist_album_path(@artist, album), class: "btn btn-secondary" %>
          <% end %>
          <% if policy(album).destroy? %>
            <%= link_to "Delete", artist_album_path(@artist, album), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/albums/new.html.erb
<div class="container">
  <div class="d-flex justify-content-start">
    <h1 class="mt-4">New Album</h1>
  </div>

  <% if policy(@album).create? %>
    <div>
      <%= simple_form_for(@album) do |f| %>
        <%= f.input :name %>
        <%= f.input :year, placeholder: 'Needs to follow the format: yyyy' %>
        <%= f.input :artist, label: "Artist:", collection: @artists %>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <%= link_to "Back to artist list", artists_path, class: "btn btn-secondary" %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/artists/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <h2 class="mt-5 border-bottom"><strong>Artists available</strong></h2>
  </div>
  <br>
  <div>
    <%= link_to "Add a new album", new_album_path, class: "btn btn-warning" %>
  </div>
  <br>
  <div class="d-flex align-content-start flex-wrap">
    <% if @artists.present? %>
      <% @artists.each do |artist| %>
        <div class="col-4 mb-3">
          <h2 class="border-bottom"><%= artist.name %></h2>
          <p><strong>Twitter:</strong> <%= artist.twitter %></p>
          <p><%= link_to "Albums", artist_albums_path(artist), class: "btn btn-primary w-100" %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div>
      <h1 class="mt-5 border-bottom text-center">Album Collection App</h1>
    <br>
      <div class="justify-content-center">
        <div class="d-flex justify-content-around flex-column mt-3 pb-3">
          <div class="row justify-content-around">
            <% unless user_signed_in? %>
              <%= link_to "Log in", new_user_session_path, class: "btn btn-primary col-5" %>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-warning col-5" %>
            <% else %>
              <%= link_to "Artist List", artists_path, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.designyourway.net/blog/wp-content/uploads/2018/12/music_logo-700x525.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Artist List", artists_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://genslerzudansdentistry.com/wp-content/uploads/2015/11/anonymous-user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-light" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>